apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordsoundboard-deployment-frontend
  labels:
    app: discordsoundboard
    tier: frontend
spec:
  selector:
    matchLabels:
      app: discordsoundboard
      tier: frontend
  template:
    metadata:
      labels:
        app: discordsoundboard
        tier: frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: discordsoundboard
          image: ghcr.io/ggresillion/discordsoundboard_frontend:${IMAGE_TAG}
          ports:
            - containerPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordsoundboard-deployment-backend
  labels:
    app: discordsoundboard
    tier: backend
spec:
  selector:
    matchLabels:
      app: discordsoundboard
      tier: backend
  template:
    metadata:
      labels:
        app: discordsoundboard
        tier: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: discordsoundboard
          image: ghcr.io/ggresillion/discordsoundboard_backend:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discordsoundboard-secret
                  key: botToken
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: discordsoundboard-secret
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: discordsoundboard-secret
                  key: clientSecret
            - name: SPOTIFY_ID
              valueFrom:
                secretKeyRef:
                  name: discordsoundboard-secret
                  key: spotifyId
            - name: SPOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: discordsoundboard-secret
                  key: spotifySecret

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discordsoundboard-secret
  namespace: default
spec:
  encryptedData:
    botToken: AgBq9raduHOQNkbFz89EU1qFqBVZXPFR2fSbRIdt48RLy9W337cQEp/8ZRVW9R6Q/G0ozEs4tX3/wnaGWT+4ciAlrSalk3pqZ9J5X93xbRLOYm6KtCwYjSWt30KqIJJpC0rCE1G1wfzlZcv3LH8mXnIcejdqrBRpmXbg89XhVYYRqe9qyXpplICkong8TtHd6JDPOf/tXh1l1dsWvXVp7wqOjUstignw5Z8cpcz+76FeLy8AnfT7YHzLYAC78Owo1GCfChbSOB73jRD2EEeRzM2q+4SQd1MPW0w0XXIFA8SqYsg0BTtSo0THHundn7vzNcv7pa8MVtX42CSy9HEK8zMB3feSJtGrFt7KnZxjU0bPUigFZNpLlN8LAUWpYV3Jx8YZJ+k0/mACPCWtc44Otnuq1GTx/7uOlUubcGUNTrSeZqTCklsMqmzErisbskD6mVhnFqkRiWali4vLvBjz2dhKYJIvjLa/MPaJgtOhpZoXxqkOwcQDDhW6yw5V/eCl80XYefaKlHfH2wL14c6LfjWgpise8yzw62Y8LDZJ33iUr8Wl0rBmX9PSYn2KKfUTyX+96Te3fj8ORUZ5XCisO92J/e+XRI5XLtLrWyfMrWI4iI7yM1DoKnWiMso2S6MBaPGcRYAAZ+Q7A/xIKOgELvk9b5kcxKYbs+Qh6zvu65YgcrDP8LZoe7RtD9ZfSnWFiGFo7eO0A1Fiw4Y8N7M6gxB4y5eRmNlD3AD87Wn7DW9m+bdzqwjorHCnthLFhlMs149uTX/Ziad2KIdLO7GvH8ycyIONPEq7
    clientId: AgDNY3WpSTWLeANQEduLR4bDg3BJck9UiUKHBACOfI4317GNN6AWmMOykGINUXkTqhFosCne/qytrTn04mqxtiFKkwdNcQbbGzyrWDuYN/nz6VGlDGWoJEjwBn52RWUWld05w3e7mbaDKlhG8BsSx3cl5jvqzUWWaybLu5no/FESnFXl4/yzhdIxniREBk/24bfTlRB9HWO9ZgbRWlBQrgFDM+sZpbAAjd/OKMnb4+G/wIgqWRPhqEVLxdpgmVK/6bgPHYgeAdRuWfxHrWX70lhox+I09Rr8N25VIdV6sABEOrxMIqobJIe6yoFrOnTbZ086u+BuJpddtj9jT40H+fBHoYQYAgzxbZHmxPqB+FxPorHGGa7UXjVOCoAnVIUL3HtetQDsOxglVcHvhExF5ZHUK4Y7blkVMRRugOodPuBEPNaCc9wdsFDc2b9uTngUcdAdbp1H2O32dNkkj6tkdfgGtkqmjiYjgfXvhbYxPSTsgGPuc5LeSPDY10RioTf6iL5YQu3o06iKFeAueJ/9yX/WcKh689JNYeaTwlpaG0lrI2EVkdvSP6mjA+mD4BTNvD0Cinqggdh5EEaE6ybN63X09BZQEWDg7QMi6G1UMjkIIGjz83Kekvf0Kvpv0wBK74OicDo5IWUY5iSsQkVDivRQXkspQG4PLDizcY4981e/QT3gBZvzLe2nI3E6uQ5UFWi1mrgXh+f1FCElLSrVsf0JE38=
    clientSecret: AgCBqmDL/i9m0mdr2YyeOCSC/T5xiwbBM08glrasoK1GlyHlHpi/VFUYuMjS24oC2khFTnE4iaU7EmFdQ0k44+vOnIu+Z6Bk0sPHX6UmxG3V6pMkabCevYZ7QLvd1P0UqEAseLKTilEFpn79aFmwnXIc0mOIL2wC28JMGFAXGuv3LanwYIAo2TDKpeFqI9waiF3V12ZBA2259gRWftbhD2OY0ewG6Zm6mt9o06TytDQkJOENv2vMdybl7xa1Rp2iJjSqET7Rj9kzhyL51L7BTCtyQAtU1Lpg0VjJic7uh66hsDTQakmcMsiTlixta/sVyx+/GzxHEbMmCYxZSLHVcu0ocCmUoZpohrXGRBBN9C0J9zpSMSuZW/R3QmwZcg7H3V1zZdEfDufxE/H7fY07nloBgnkiQH1EKtIerkKzyuXgEXxF/fVemE3FaJlFNcgLMI/Nu3agLtZdO305UOk5cRaL3i+8T0+KklquXR6jF9v08lKmXghSNhB4lpB41xGpyMpdRhxAP3xva6AcWgExjWmSkAqwP+Lf9wu2XfaAfBrANZyHCceLHxNpxLB46ZPQSdgg5ScqrbwJ/BWbqL3ANNSlgrMF2HI1Cm0rgYXalaA8VA2eLHN9JqrDxwd4/zbk36yOJh/KQ8+r227jD9wKQGqTfNLF0lAllUx7SYqNhuJRxiGZ2wPFcLuB5yAsnrIUP9YBgD9rfUohjth0lwdsHAsdWKem1qiO+htSlbSDHKsstQ==
    spotifyId: AgCcSCkwv9jfxvQ9ALgoEiuNlAutnuIRBXwUSzQelv11vZQLQgd0NTxJR9DMBh8yk0vH3nfxm5oOci6lpZ7QWip8keydA1CfqmmJHNqDGut+LbSzLiOIMF2pJjo3ijlg5iDMjzKCGKznDFKjy+8/K/B+ZXxhkxcB5jrwN+ecloVmdYbL9sNALTAhX2acU7atQsOMjmDUKe8d+XlQQ/qULWnvwmMBMUx1eXGWxiZQpCa0CNgPAtMAYFZfJyZ4D4aMD7pQIbRZHz3CKlJZ9ItJO3agQ16OE1Yzy+C9le2SZJFqW95FV7mlLUZhLJFscPMBsCw000qMn+LiJO00s+TbY51h0+/VLsQ+Nl7iTmumqxxv1XagMpXDhMCYsLIf2hEkv7tEdjlRPcWGeha+vbVnfAEyjb052mVJB26jFCFGIqOKvvRZ36AeMOW8u5dxhdvpC95MHTW6wrhJ9U8XFxhwDI4+c7nwZP8OTSafWgsAZ+ejKxMmDFnQfoGxCSCsQapf0sX30aI1mkMNsZjiGheSYnj1NXLc5ooKlEnU8eLAFfPCOIYvVuHcZ3sxYTZSQEByfi26qPUpmrVUVvwpu72RqYC6S2cybW4USF9/rt1uGk/X70I0cqIw7EyuPvQJnqV5p4tuIwPBA5qV500t0ZV+ZYzvNCNKJuanle6YT40Np+JMitpuqANXB4d/6MKTH5qY08z3m58T4QoHghP5G2AOUdH7cE4KgGEQYU1KmgzLng2b0g==
    spotifySecret: AgCgVQCXMRELBlITlzvS0+2qfP7+668wDl+7OLfdzXqYdcN6UJrYB7J8ksvzpzR8JFQ/lZILlAatiA1wCfENQtAY0dz36/+/1gJhoNIz4An/2oYb+SJfgkDB3moAA12OkbH+zN8FD1sbN9BRoZ32h5gieCQUamgfQKA7T5qtTbaK2LaJIzYupoZJD/NKMBEd4u6IipHFP8/Ci3winTchHd1GQKdlvRjsbTl6UM1VmlFm21S5xGB8eYnldP2fXsWuhKYjIlSPi4c+ScU7XCWVRgzIwkglANSkadx/9rTPO+/Fyb9DmBMai4hr7rTRj0kRaTSgQIZc7ooicaL3vGFk4yEHATRGlqqEmUoHlEdQns6Xt/GlUY2vRiLNSwJ2h5lBNzSaersQ6Gz14jwCV5zNpzmIfMbctJY5hYUa4UYAAKfQQLOaijABA4rRWisbv7h0076mbpce+GFRqW8Yp6cJI9M3Ne81nKr1mSMHVcSigXcJSoqoj+2kkRaNzFTZQV4Bipl01E8f+a13q4Q9HDEPgTLoAY3M47Fe1O3sk2jQFTvwPfcMEVKnmY/UPbBTGpu+i1IcJNcdTN3ZrpFWvVj6O5yJP7X6VaKy0TVc0Gemr++ETYn6ha6SH+pF+g/RHifNK1z6GsgioHokR+0jh9jdZ0liqfhoblJDW2XpM/ALYtiFd2eLkCPsBSBL1EECRroKLRr9YJTSfayFedpOu56W1UE8mdb84P55rh/tD1ocWFgeRw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: discordsoundboard-secret
      namespace: default
    type: Opaque

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBZH6vFN7L8YsaQIqqkBXFeT5f46mj5diQdotoBtl9UyQd9zjbqHVbT7dAl9J/NwHjffmAQ+yQZyPSq8Zs3TPb/F0U94lkM3xLYmIAUntX3X6DR9K5glkvtZa4LgiyTu1kWDJYzJ8lCaHHr6NaiZaEUjdHrnAFy3aSBAz256nDfbf+v/138a6lOysUJNirhMI+nNSD8r7hPJx74jHOVrO6KauCnw3O9iZmPiRn3H1ZQu5OJaPoGpsfL7TaAd1LN5tWQgTmdavZbntrXjVnEoRLt8Jv23ezdwaCHLLu2EhR27mK1oY+uvTaT37bX2jBQlZKgmZTAQaotAIf2T2B9VrKPe7FiAoGzUdp/UgLIczb51Xr19NSkd+Y4/cIZ/SLwFDgNMoCR3DwwtQP4wBmqL3677x1BY0RzC9SPL8MVDUee4G5yCgNZz+MvWxNS4y98SuZwyA2gI+Fl/W5uwCHWyzPR12DMcf8781TZq1OD2zoQkb/Ua3LrZjhsaWSynlgNYLOUKualEuz+7bVCzcBUZUeZ6b7ne0afAD1FoNgr3I2S9vbYQAUZ/65i7sRbUqYTtdnsD7WFkd2N6k3rWmRKbGWZ7kl43cg7pvQ28y6hFYDBkkm9p2pCa5mMZMXmodpWFcAet4FCOCeRZYaZWZpjQL5WvtKjiIyQoPLPTaEgKGKAA7ybJuhCRXycwqiFa2V+7xv9+3Sw/ap4oejEd7FejmCOnOeKU+XlTDP+ONbawHkqXjvLk7NAmDfdHqOwx9l33vgiRH6eNWHklkvDhr7NHXRjpM9DhoD9kUKOR6R66PLc11Dw6PYwp81RmZSIf8Uzg68QxG+vSjjDEK74iKytlZFnvEX5LtUVJA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Service
metadata:
  name: discordsoundboard-service
spec:
  selector:
    app: discordsoundboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discordsoundboard-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: discordsoundboard-service
                port:
                  number: 80
