apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    tier: client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      tier: client
  template:
    metadata:
      labels:
        tier: client
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          image: "{{ .Values.repository }}/{{ .Values.client.image }}:{{ .Values.client.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

---

apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    tier: client
  