apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discordsoundboard.fullname" . }}
  labels:
    {{- include "discordsoundboard.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "discordsoundboard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "discordsoundboard.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: discordsoundboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8080
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: botToken
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: clientSecret
