apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  clientId: {{ .Values.secrets.clientId | toString | b64enc | quote }}
  clientSecret: {{ .Values.secrets.clientSecret | b64enc | quote }}
  botToken: {{ .Values.secrets.botToken | b64enc | quote }}
