apiVersion: v1
kind: Secret
metadata:
  name: discordsounboard
type: Opaque
{{- $previous := lookup "v1" "Secret" .Release.Namespace "discordsounboard" }}
data:
  {{- if $previous }}
  botToken: {{ $previous.data.botToken }}
  {{- else if .Values.secret.botToken }}
  botToken: {{ .Values.secret.botToken | b64enc | quote }}
  {{- else }}
  botToken:
  {{- end }}

  {{- if $previous }}
  clientId: {{ $previous.data.clientId }}
  {{- else if .Values.secret.clientId }}
  clientId: {{ .Values.secret.clientId | toString | b64enc | quote }}
  {{- else }}
  clientId:
  {{- end }}

  {{- if $previous }}
  clientSecret: {{ $previous.data.clientSecret }}
  {{- else if .Values.secret.clientSecret }}
  clientSecret: {{ .Values.secret.clientSecret | b64enc | quote }}
  {{- else }}
  clientSecret:
  {{- end }}