apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordsoundboard-deployment-backend
  labels:
    app: discordsoundboard
    tier: backend
spec:
  selector:
    matchLabels:
      app: discordsoundboard
      tier: backend
  template:
    metadata:
      labels:
        app: discordsoundboard
        tier: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: discordsoundboard
          image: ghcr.io/ggresillion/discordsoundboard_backend:1.0.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discordsoundboard-secret
                  key: botToken
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: discordsoundboard-secret
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: discordsoundboard-secret
                  key: clientSecret
            - name: SPOTIFY_ID
              valueFrom:
                secretKeyRef:
                  name: discordsoundboard-secret
                  key: spotifyId
            - name: SPOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: discordsoundboard-secret
                  key: spotifySecret