package youtube

type Video struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Formats []struct {
		FormatID   string  `json:"format_id"`
		FormatNote string  `json:"format_note"`
		Ext        string  `json:"ext"`
		Protocol   string  `json:"protocol"`
		Acodec     string  `json:"acodec"`
		Vcodec     string  `json:"vcodec"`
		URL        string  `json:"url"`
		Width      int     `json:"width"`
		Height     int     `json:"height"`
		FPS        float64 `json:"fps"`
		Rows       int     `json:"rows"`
		Columns    int     `json:"columns"`
		Fragments  []struct {
			URL      string  `json:"url"`
			Duration float64 `json:"duration"`
		} `json:"fragments"`
		AudioExt       string            `json:"audio_ext"`
		VideoExt       string            `json:"video_ext"`
		Vbr            float64           `json:"vbr"`
		Abr            float64           `json:"abr"`
		Tbr            interface{}       `json:"tbr"`
		Resolution     string            `json:"resolution"`
		AspectRatio    float64           `json:"aspect_ratio"`
		FilesizeApprox interface{}       `json:"filesize_approx"`
		HTTPHeaders    map[string]string `json:"http_headers"`
		Format         string            `json:"format"`
	} `json:"formats"`
	Thumbnails []struct {
		URL        string `json:"url"`
		Preference int    `json:"preference"`
		ID         string `json:"id"`
	} `json:"thumbnails"`
	Thumbnail         string      `json:"thumbnail"`
	Description       string      `json:"description"`
	ChannelID         string      `json:"channel_id"`
	ChannelURL        string      `json:"channel_url"`
	Duration          int         `json:"duration"`
	ViewCount         int         `json:"view_count"`
	AverageRating     interface{} `json:"average_rating"`
	AgeLimit          int         `json:"age_limit"`
	WebpageURL        string      `json:"webpage_url"`
	Categories        []string    `json:"categories"`
	Tags              []string    `json:"tags"`
	PlayableInEmbed   bool        `json:"playable_in_embed"`
	LiveStatus        string      `json:"live_status"`
	ReleaseTimestamp  interface{} `json:"release_timestamp"`
	FormatSortFields  []string    `json:"_format_sort_fields"`
	AutomaticCaptions map[string][]struct {
		Ext  string `json:"ext"`
		URL  string `json:"url"`
		Name string `json:"name"`
	} `json:"automatic_captions"`
	Subtitles    map[string]interface{} `json:"subtitles"`
	CommentCount int                    `json:"comment_count"`
	Chapters     interface{}            `json:"chapters"`
	Heatmap      []struct {
		StartTime float64 `json:"start_time"`
		EndTime   float64 `json:"end_time"`
		Value     float64 `json:"value"`
	} `json:"heatmap"`
	LikeCount            int         `json:"like_count"`
	Channel              string      `json:"channel"`
	ChannelFollowerCount int         `json:"channel_follower_count"`
	ChannelIsVerified    bool        `json:"channel_is_verified"`
	Uploader             string      `json:"uploader"`
	UploaderID           string      `json:"uploader_id"`
	UploaderURL          string      `json:"uploader_url"`
	UploadDate           string      `json:"upload_date"`
	Timestamp            int         `json:"timestamp"`
	Availability         string      `json:"availability"`
	OriginalURL          string      `json:"original_url"`
	WebpageURLBasename   string      `json:"webpage_url_basename"`
	WebpageURLDomain     string      `json:"webpage_url_domain"`
	Extractor            string      `json:"extractor"`
	ExtractorKey         string      `json:"extractor_key"`
	Playlist             interface{} `json:"playlist"`
	PlaylistIndex        interface{} `json:"playlist_index"`
	DisplayID            string      `json:"display_id"`
	Fulltitle            string      `json:"fulltitle"`
	DurationString       string      `json:"duration_string"`
	ReleaseYear          interface{} `json:"release_year"`
	IsLive               bool        `json:"is_live"`
	WasLive              bool        `json:"was_live"`
	RequestedSubtitles   interface{} `json:"requested_subtitles"`
	Epoch                int         `json:"epoch"`
	RequestedDownloads   []struct {
		Asr                int     `json:"asr"`
		Filesize           int     `json:"filesize"`
		FormatID           string  `json:"format_id"`
		FormatNote         string  `json:"format_note"`
		SourcePreference   int     `json:"source_preference"`
		AudioChannels      int     `json:"audio_channels"`
		Quality            float64 `json:"quality"`
		HasDRM             bool    `json:"has_drm"`
		Tbr                float64 `json:"tbr"`
		FilesizeApprox     int     `json:"filesize_approx"`
		URL                string  `json:"url"`
		Language           string  `json:"language"`
		LanguagePreference int     `json:"language_preference"`
		Ext                string  `json:"ext"`
		Vcodec             string  `json:"vcodec"`
		Acodec             string  `json:"acodec"`
		Container          string  `json:"container"`
		DownloaderOptions  struct {
			HTTPChunkSize int `json:"http_chunk_size"`
		} `json:"downloader_options"`
		Protocol             string            `json:"protocol"`
		AudioExt             string            `json:"audio_ext"`
		VideoExt             string            `json:"video_ext"`
		Vbr                  float64           `json:"vbr"`
		Abr                  float64           `json:"abr"`
		Resolution           string            `json:"resolution"`
		HTTPHeaders          map[string]string `json:"http_headers"`
		Format               string            `json:"format"`
		Filename             string            `json:"_filename"`
		WriteDownloadArchive bool              `json:"__write_download_archive"`
	} `json:"requested_downloads"`
	Asr                int         `json:"asr"`
	Filesize           int         `json:"filesize"`
	FormatID           string      `json:"format_id"`
	FormatNote         string      `json:"format_note"`
	SourcePreference   int         `json:"source_preference"`
	FPS                interface{} `json:"fps"`
	AudioChannels      int         `json:"audio_channels"`
	Height             interface{} `json:"height"`
	Quality            float64     `json:"quality"`
	HasDRM             bool        `json:"has_drm"`
	Tbr                float64     `json:"tbr"`
	FilesizeApprox     int         `json:"filesize_approx"`
	URL                string      `json:"url"`
	Width              interface{} `json:"width"`
	Language           string      `json:"language"`
	LanguagePreference int         `json:"language_preference"`
	Preference         interface{} `json:"preference"`
	Ext                string      `json:"ext"`
	Vcodec             string      `json:"vcodec"`
	Acodec             string      `json:"acodec"`
	DynamicRange       interface{} `json:"dynamic_range"`
	Container          string      `json:"container"`
	DownloaderOptions  struct {
		HTTPChunkSize int `json:"http_chunk_size"`
	} `json:"downloader_options"`
	Protocol    string            `json:"protocol"`
	AudioExt    string            `json:"audio_ext"`
	VideoExt    string            `json:"video_ext"`
	Vbr         float64           `json:"vbr"`
	Abr         float64           `json:"abr"`
	Resolution  string            `json:"resolution"`
	AspectRatio interface{}       `json:"aspect_ratio"`
	HTTPHeaders map[string]string `json:"http_headers"`
	Format      string            `json:"format"`
	Type        string            `json:"_type"`
	Version     struct {
		Version        string      `json:"version"`
		CurrentGitHead interface{} `json:"current_git_head"`
		ReleaseGitHead interface{} `json:"release_git_head"`
		Repository     string      `json:"repository"`
	} `json:"_version"`
}
