name: Update kubernetes manifests

on:
  push:
    branches: ["master"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Kubernetes tools
        uses: stefanprodan/kube-tools@v1
        with:
          helmv3: 3.7.2
          command: |
            helmv3 upgrade --install --set image.tag=${{ steps.meta.outputs.tags }} discordsounboard chart
