// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		user := userFromCtx(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex w-full items-center gap-4 border-b border-white/10 bg-gradient-to-b from-[rgba(20,20,40,0.8)] to-[rgba(16,16,32,0.9)] backdrop-blur-xl px-6 py-4\"><h1 class=\"text-2xl font-extrabold tracking-wide bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent\">Raver</h1><div class=\"flex gap-1 h-6 items-end ml-2\"><div class=\"w-1.5 rounded-full bg-gradient-to-t from-purple-500 to-pink-500 animate-[viz_1.2s_ease-in-out_infinite]\"></div><div class=\"w-1.5 rounded-full bg-gradient-to-t from-purple-500 to-pink-500 animate-[viz_0.9s_ease-in-out_infinite]\"></div><div class=\"w-1.5 rounded-full bg-gradient-to-t from-purple-500 to-pink-500 animate-[viz_0.7s_ease-in-out_infinite]\"></div><div class=\"w-1.5 rounded-full bg-gradient-to-t from-purple-500 to-pink-500 animate-[viz_0.9s_ease-in-out_infinite]\"></div><div class=\"w-1.5 rounded-full bg-gradient-to-t from-purple-500 to-pink-500 animate-[viz_1.2s_ease-in-out_infinite]\"></div></div><div class=\"ml-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = userIcon(user).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><style>\n\t\t\t@keyframes viz {\n\t\t\t\t0%, 100% { height: 20%; }\n\t\t\t\t50% { height: 100%; }\n\t\t\t}\n\t\t</style></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func userIcon(user User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<details class=\"group relative flex flex-row gap-3 items-center cursor-pointer\"><summary class=\"flex items-center list-none rounded-full ring-2 ring-purple-500/50 ring-offset-2 ring-offset-transparent hover:ring-purple-400 transition-all duration-300\"><img class=\"w-9 h-9 rounded-full object-cover\" src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue("https://cdn.discordapp.com/avatars/" + user.ID + "/" + user.Avatar + ".png")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/header.templ`, Line: 37, Col: 132}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"></summary><!-- Dropdown Menu --><div class=\"absolute right-0 top-full mt-3 w-56 z-50 rounded-2xl bg-gradient-to-b from-[rgba(30,30,60,0.95)] to-[rgba(20,20,40,0.95)] backdrop-blur-xl border border-white/10 shadow-[0_20px_40px_-15px_rgba(0,0,0,0.5),0_0_0_1px_rgba(255,255,255,0.05)] overflow-hidden opacity-0 invisible group-open:opacity-100 group-open:visible transition-all duration-300 transform translate-y-2 group-open:translate-y-0\"><!-- User Info --><div class=\"px-4 py-3 border-b border-white/10\"><p class=\"text-sm font-semibold text-white truncate\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(user.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/header.templ`, Line: 53, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</p><p class=\"text-xs text-white/50\">Connected to Raver</p></div><!-- Menu Items --><div class=\"py-2\"><form method=\"POST\" action=\"/auth/logout\" class=\"w-full\"><button type=\"submit\" class=\"w-full flex items-center gap-3 px-4 py-2.5 text-left text-sm text-red-400 hover:bg-red-500/10 hover:text-red-300 transition-colors duration-200\"><i class=\"bi bi-box-arrow-right\"></i> <span>Disconnect</span></button></form></div><!-- Decorative gradient line --><div class=\"h-1 w-full bg-gradient-to-r from-purple-500 via-pink-500 to-purple-500\"></div></div></details>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
